;-*- mode: emacs-lisp -*-

(source org)
(source marmalade)
(source melpa)

(depends-on "org-plus-contrib")
(depends-on "helm")
(depends-on "helm-ls-git")
(depends-on "helm-pydoc")
(depends-on "helm-dash")
(depends-on "popwin")
(depends-on "auto-complete")
(depends-on "jedi")
(depends-on "go-mode")
(depends-on "go-autocomplete")
(depends-on "go-eldoc")
(depends-on "clojure-mode")
(depends-on "cider")
(depends-on "ac-nrepl")
(depends-on "w3m")
